// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAH4910GfdmTYM7O3yWHNKR9lNOcdZy-BM',
//     appId: '1:74539148537:web:f7592ab3c57de32f7cae28',
//     messagingSenderId: '74539148537',
//     projectId: 'atm-go',
//     authDomain: 'atm-go.firebaseapp.com',
//     storageBucket: 'atm-go.firebasestorage.app',
//     measurementId: 'G-8P7SEDDCHC',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBeYpaMqNEGBiEq5Ogq_VR1yY565K-fIUc',
//     appId: '1:74539148537:android:2dcb2cd0d2c1494c7cae28',
//     messagingSenderId: '74539148537',
//     projectId: 'atm-go',
//     storageBucket: 'atm-go.firebasestorage.app',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCkVVoLnAonJ0bzCCRY57-ToVzpQA6qy9g',
//     appId: '1:74539148537:ios:1f3cd1bc0585dfc57cae28',
//     messagingSenderId: '74539148537',
//     projectId: 'atm-go',
//     storageBucket: 'atm-go.firebasestorage.app',
//     iosBundleId: 'com.example.atmGo',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyCkVVoLnAonJ0bzCCRY57-ToVzpQA6qy9g',
//     appId: '1:74539148537:ios:1f3cd1bc0585dfc57cae28',
//     messagingSenderId: '74539148537',
//     projectId: 'atm-go',
//     storageBucket: 'atm-go.firebasestorage.app',
//     iosBundleId: 'com.example.atmGo',
//   );
//
//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyAH4910GfdmTYM7O3yWHNKR9lNOcdZy-BM',
//     appId: '1:74539148537:web:9fe56810e2f859067cae28',
//     messagingSenderId: '74539148537',
//     projectId: 'atm-go',
//     authDomain: 'atm-go.firebaseapp.com',
//     storageBucket: 'atm-go.firebasestorage.app',
//     measurementId: 'G-SKTVFMJN8S',
//   );
// }
